### ISSUE TITLE
ClearVolume + MATLAB

### ISSUE THREAD

**Issue by ctrueden** [ClearVolume/imglib2-clearvolume#14]
From Andres Barragan [via the ImageJ mailing list](http://imagej.1557.x6.nabble.com/Clear-Volume-with-MIJ-Tool-that-helps-connect-ImageJ-to-MATLAB-tp5020996p5021058.html):

> ClearVolume appears now in the plugins but I am getting an exception. Any ideas? For some reason I do not get this exception when simply running the executable of ImageJ.
>
> ```
> (Fiji Is Just) ImageJ 2.0.0-rc-68/1.52e; Java 1.8.0_144 [64-bit]; Windows 10 10.0; 320MB of 1910MB (16%)
> 
> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
> 	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
> 	at ij.IJ.runPlugIn(IJ.java)
> 	at ij.Executer.runCommand(Executer.java:137)
> 	at ij.Executer.run(Executer.java:66)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
> 	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:299)
> 	... 5 more
> Caused by: java.lang.NullPointerException
> 	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initClearVolumeUnsignedShortArrayImg(ImgLib2ClearVolume.java:284)
> 	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initRealImgs(ImgLib2ClearVolume.java:511)
> 	at de.mpicbg.jug.clearvolume.gui.ClearVolumeManager.run(ClearVolumeManager.java:182)
> 	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.launchClearVolumeManager(GenericClearVolumeGui.java:306)
> 	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.<init>(GenericClearVolumeGui.java:163)
> 	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:90)
> 	at org.scijava.command.CommandModule.run(CommandModule.java:199)
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
> 	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	... 1 more
> ```

I investigated a little, and based on [the relevant code](https://github.com/ClearVolume/imglib2-clearvolume/blob/imglib-clearvolume-1.3.22/src/main/java/de/mpicbg/jug/clearvolume/ImgLib2ClearVolume.java#L261-L284), I guess that `ClearVolumeRendererFactory.newBestRenderer` and/or `ClearVolumeRendererFactory.newOpenCLRenderer` must be returning null. But more investigation required to discern why that would be the case from a MATLAB environment.

**Comment by royerloic** [comment]
You should be using the main branch (master) instead of a deprecated branch (your link points to very very old code...)

**Comment by ctrueden** [comment]
> (your link points to very very old code...)

Dude, it is the latest tag. And the last commit to touch that source file is the same on master still.

**Comment by royerloic** [comment]
Oh I see, I saw some cuda flags and assumed it was very old code.
I would test in FiJi first and see how it goes, my guess is that there is
a GPU, GPU driver problem, or the native libs of JOCL are missing...

**Comment by ctrueden** [comment]
I am guessing this is a MATLAB-specific issue; from the original thread, it sounds like the plugin works when launched from Fiji normally.

I was thinking it might be some subtle thing with MATLAB's JRE, but upon reflection, perhaps it is as simple as the JARs from the `jars/<platform>` folder not being added to MATLAB's classpath.

I do not have time to test it, but Andreas, if you are reading this: you could try:
```matlab
javaaddpath 'C:\Users\andreas\Fiji.app\jars\win64'
```
And see if that makes a difference. See the [javaaddpath documentation](https://www.mathworks.com/help/matlab/ref/javaaddpath.html) for details.

**Comment by mynameisandres** [comment]
ctrueden, I attempted your solution.

I did

`javaaddpath 'C:\Users\Swag\Documents\4D-SoftwareChet\ae4d-master\Fiji.app\jars\win64'`

My MatLab Execution was
`>> addpath('C:\Users\Swag\Documents\4D-SoftwareChet\ae4d-master\Fiji.app\scripts');
>> javaaddpath 'C:\Users\Swag\Documents\4D-SoftwareChet\ae4d-master\Fiji.app\jars\win64'
>> ImageJ;
--------------------------------------------------------------
ImageJ-MATLAB 0.7.2: MATLAB to ImageJ Interface
--------------------------------------------------------------
JVM> Version: 1.8.0_144
JVM> Total amount of memory: 514048 Kb
JVM> Amount of free memory: 169641 Kb

-- Welcome to ImageJ-MATLAB --
ImageJ-MATLAB consists of an extensible set of commands for passing information between ImageJ and MATLAB.
See the individual sections below for a list of available commands.

For more information and examples see:
	http://imagej.net/MATLAB-Scripting

--- MATLAB Command Plugins ---

-- ImageJ MATLAB commands --

Usage: IJM.[command]
	help - prints a brief description of available commands
	getDataset - creates a MATLAB matrix from the active ImageJ image
	getDatasetAs(name) - creates a MATLAB matrix from the active ImageJ image, and assigns it to the specified variable name
	show(name) - takes the MATLAB matrix with the specified name and displays it as an image



--------------------------------------------------------------
Status> ImageJ is running.
--------------------------------------------------------------
log4j:WARN No appenders could be found for logger (loci.formats.ClassList).
log4j:WARN Please initialize the log4j system properly.
null
ClearGLWindow: GLProfile[GL4bc/GL4bc.hw]
java.lang.ExceptionInInitializerError
	at cleargl.ClearGLWindow.<init>(ClearGLWindow.java:150)
	at cleargl.ClearGLWindow.<init>(ClearGLWindow.java:118)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.<init>(ClearGLVolumeRenderer.java:359)
	at clearvolume.renderer.opencl.OpenCLVolumeRenderer.<init>(OpenCLVolumeRenderer.java:110)
	at clearvolume.renderer.opencl.OpenCLVolumeRenderer.<init>(OpenCLVolumeRenderer.java:89)
	at clearvolume.renderer.factory.ClearVolumeRendererFactory.internalCreateOpenCLRenderer(ClearVolumeRendererFactory.java:288)
	at clearvolume.renderer.factory.ClearVolumeRendererFactory.newOpenCLRenderer(ClearVolumeRendererFactory.java:253)
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initClearVolumeUnsignedShortArrayImg(ImgLib2ClearVolume.java:273)
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initRealImgs(ImgLib2ClearVolume.java:511)
	at de.mpicbg.jug.clearvolume.gui.ClearVolumeManager.run(ClearVolumeManager.java:182)
	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.launchClearVolumeManager(GenericClearVolumeGui.java:306)
	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.<init>(GenericClearVolumeGui.java:163)
	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:90)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Property 'newt.window.icons' did not specify at least two PNG icons, but [null,null]
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:64)
	... 22 more
[ERROR] Module threw exception

java.lang.NullPointerException

	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initClearVolumeUnsignedShortArrayImg(ImgLib2ClearVolume.java:284)

	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initRealImgs(ImgLib2ClearVolume.java:511)

	at de.mpicbg.jug.clearvolume.gui.ClearVolumeManager.run(ClearVolumeManager.java:182)

	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.launchClearVolumeManager(GenericClearVolumeGui.java:306)

	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.<init>(GenericClearVolumeGui.java:163)

	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:90)

	at org.scijava.command.CommandModule.run(CommandModule.java:199)

	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)

	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)

	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)

	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

>> `

Than I recieved error when attempted to open the MRI stack on ClearVolume as a test:
`(Fiji Is Just) ImageJ 2.0.0-rc-68/1.52g; Java 1.8.0_144 [64-bit]; Windows 10 10.0; 270MB of 1923MB (14%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:299)
	... 5 more
Caused by: java.lang.NullPointerException
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initClearVolumeUnsignedShortArrayImg(ImgLib2ClearVolume.java:284)
	at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.initRealImgs(ImgLib2ClearVolume.java:511)
	at de.mpicbg.jug.clearvolume.gui.ClearVolumeManager.run(ClearVolumeManager.java:182)
	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.launchClearVolumeManager(GenericClearVolumeGui.java:306)
	at de.mpicbg.jug.clearvolume.gui.GenericClearVolumeGui.<init>(GenericClearVolumeGui.java:163)
	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:90)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
`
