### ISSUE TITLE
java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT

### ISSUE THREAD

**Issue by haesleinhuepf** [ClearVolume/imglib2-clearvolume#16]
Hey guys,

I just wanted to check if the current build works inside Fiji, before we update the update site. However, when trying to open T1-head.tif in ClearVolume, this error message comes up. I just downloaded the recent master branch (2019-03-25), and used mvn install to install it to my Fiji.

Do I have to install some additional Jogamp dependency manually?

Cheers,
Robert

(Fiji Is Just) ImageJ 2.0.0-rc-71/1.52i; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 61MB of 12101MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:299)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: com/jogamp/newt/awt/NewtCanvasAWT
	at de.mpicbg.jug.plugins.ClearVolumePlugin.run(ClearVolumePlugin.java:90)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.jogamp.newt.awt.NewtCanvasAWT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

**Comment by imagejan** [comment]
When running *Plugins > Utilities > Find Jar For Class*, I get:

```
The class com.jogamp.newt.awt.NewtCanvasAWT is contained in /[...]/Fiji.app/jars/jogl-all-2.3.2.jar
```

... and `jogl-all-2.3.2.jar` seems to be shipped by the **Java-8** update site. Is there any third-party update site introducing version skew for you?

**Comment by skalarproduktraum** [comment]
Hi guys,

the same problem occurs with scenery and the reason is the installer plugin's inability to figure out natives. CV does not have too many dependencies, and we copied them manually to fix this. In sciview, this is done by a script.

As this has nothing to do with imglib2-clearvolume, I'll close this for now.
