### ISSUE TITLE
not starting ununtu 20

### ISSUE THREAD

**Issue by orena1** [ClearVolume/imglib2-clearvolume#18]
```bash
(base) amsalem@amsalem-Kubuntu-home:~$ uname -a
Linux amsalem-Kubuntu-home 5.8.0-43-generic #49-Ubuntu SMP Fri Feb 5 03:01:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(base) amsalem@amsalem-Kubuntu-home:~$ clinfo 
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
Number of platforms                               2
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
  Platform Extensions function suffix             Intel
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [2]
param: 4, val: 0
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)

  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3052.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 0
```

error in console
```
null
ClearGLWindow: GLProfile[GL4/GL4.hw]
1.0
1.0
1.0
LinuxFeb 17, 2021 5:39:10 PM org.bridj.BridJ log
INFO: Library not found : atiocl64
Feb 17, 2021 5:39:10 PM org.bridj.BridJ log
INFO: Library not found : amdocl64
Feb 17, 2021 5:39:10 PM org.bridj.BridJ log
INFO: Library not found : atiocl32
Feb 17, 2021 5:39:10 PM org.bridj.BridJ log
INFO: Library not found : atiocl
Feb 17, 2021 5:39:10 PM org.bridj.BridJ log
INFO: Library not found : amdocl32
Feb 17, 2021 5:39:10 PM org.bridj.BridJ log
INFO: Library not found : amdocl
clearcl.exceptions.OpenCLException: OpenCL error: -1 -> CL_DEVICE_NOT_FOUND
	at clearcl.backend.BackendUtils.checkOpenCLError(BackendUtils.java:346)
	at clearcl.backend.jocl.ClearCLBackendJOCL.lambda$getNumberOfDevicesForPlatform$4(ClearCLBackendJOCL.java:135)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.jocl.ClearCLBackendJOCL.getNumberOfDevicesForPlatform(ClearCLBackendJOCL.java:133)
	at clearcl.backend.jocl.ClearCLBackendJOCL.lambda$getNumberOfDevicesForPlatform$3(ClearCLBackendJOCL.java:125)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.jocl.ClearCLBackendJOCL.getNumberOfDevicesForPlatform(ClearCLBackendJOCL.java:124)
	at clearcl.ClearCLPlatform.getNumberOfDevices(ClearCLPlatform.java:59)
	at clearcl.ClearCL.getAllDevices(ClearCL.java:236)
	at clearcl.benchmark.Benchmark.getFastestDevice(Benchmark.java:60)
	at clearcl.backend.ClearCLBackends.isFunctionalBackend(ClearCLBackends.java:63)
	at clearcl.backend.ClearCLBackends.getFunctionalBackend(ClearCLBackends.java:83)
	at clearcl.backend.ClearCLBackends.getBestBackend(ClearCLBackends.java:105)
	at clearvolume.renderer.opencl.OpenCLDevice.initCL(OpenCLDevice.java:50)
	at clearvolume.renderer.opencl.OpenCLVolumeRenderer.initVolumeRenderer(OpenCLVolumeRenderer.java:132)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.init(ClearGLVolumeRenderer.java:824)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
clearcl.exceptions.OpenCLException: OpenCL error: -1 -> CL_DEVICE_NOT_FOUND
	at clearcl.backend.BackendUtils.checkOpenCLError(BackendUtils.java:346)
	at clearcl.backend.javacl.ClearCLBackendJavaCL.lambda$getNumberOfDevicesForPlatform$4(ClearCLBackendJavaCL.java:138)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.javacl.ClearCLBackendJavaCL.getNumberOfDevicesForPlatform(ClearCLBackendJavaCL.java:136)
	at clearcl.backend.javacl.ClearCLBackendJavaCL.lambda$getNumberOfDevicesForPlatform$3(ClearCLBackendJavaCL.java:128)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.javacl.ClearCLBackendJavaCL.getNumberOfDevicesForPlatform(ClearCLBackendJavaCL.java:127)
	at clearcl.ClearCLPlatform.getNumberOfDevices(ClearCLPlatform.java:59)
	at clearcl.ClearCL.getAllDevices(ClearCL.java:236)
	at clearcl.benchmark.Benchmark.getFastestDevice(Benchmark.java:60)
	at clearcl.backend.ClearCLBackends.isFunctionalBackend(ClearCLBackends.java:63)
	at clearcl.backend.ClearCLBackends.getFunctionalBackend(ClearCLBackends.java:83)
	at clearcl.backend.ClearCLBackends.getBestBackend(ClearCLBackends.java:105)
	at clearvolume.renderer.opencl.OpenCLDevice.initCL(OpenCLDevice.java:50)
	at clearvolume.renderer.opencl.OpenCLVolumeRenderer.initVolumeRenderer(OpenCLVolumeRenderer.java:132)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.init(ClearGLVolumeRenderer.java:824)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
 --> Using backend: ClearCLBackendJOCL
clearcl.backend.jocl.ClearCLBackendJOCL@7796998
clearcl.exceptions.OpenCLException: OpenCL error: -1 -> CL_DEVICE_NOT_FOUND
	at clearcl.backend.BackendUtils.checkOpenCLError(BackendUtils.java:346)
	at clearcl.backend.jocl.ClearCLBackendJOCL.lambda$getNumberOfDevicesForPlatform$4(ClearCLBackendJOCL.java:135)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.jocl.ClearCLBackendJOCL.getNumberOfDevicesForPlatform(ClearCLBackendJOCL.java:133)
	at clearcl.backend.jocl.ClearCLBackendJOCL.lambda$getNumberOfDevicesForPlatform$3(ClearCLBackendJOCL.java:125)
	at clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:156)
	at clearcl.backend.jocl.ClearCLBackendJOCL.getNumberOfDevicesForPlatform(ClearCLBackendJOCL.java:124)
	at clearcl.ClearCLPlatform.getNumberOfDevices(ClearCLPlatform.java:59)
	at clearcl.ClearCL.getAllDevices(ClearCL.java:236)
	at clearvolume.renderer.opencl.OpenCLDevice.initCL(OpenCLDevice.java:57)
	at clearvolume.renderer.opencl.OpenCLVolumeRenderer.initVolumeRenderer(OpenCLVolumeRenderer.java:132)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.init(ClearGLVolumeRenderer.java:824)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667)
	at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:431)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

Thanks

**Comment by Thalla** [comment]
Gibt es hierzu eine Lösung? Ich bekomme die gleiche Fehlermeldung. (aktueller Ubuntu Container mit der aktuellen Fiji stable Version)
